repositories: {  }
packagist_packages:
    - vlucas/phpdotenv
    - symfony/var-dumper
    - symfony/translation
    - symfony/security-core
    - symfony/routing
    - symfony/process
    - psr/log
    - symfony/debug
    - symfony/http-foundation
    - symfony/event-dispatcher
    - symfony/http-kernel
    - symfony/finder
    - symfony/console
    - swiftmailer/swiftmailer
    - jakub-onderka/php-console-color
    - jakub-onderka/php-console-highlighter
    - dnoegel/php-xdg-base-dir
    - nikic/php-parser
    - psy/psysh
    - nesbot/carbon
    - mtdowling/cron-expression
    - monolog/monolog
    - league/flysystem
    - jeremeamia/superclosure
    - ircmaxell/password-compat
    - doctrine/inflector
    - danielstjules/stringy
    - symfony/filesystem
    - classpreloader/classpreloader
    - laravel/framework
    - sebastian/version
    - sebastian/global-state
    - sebastian/recursion-context
    - sebastian/exporter
    - sebastian/environment
    - sebastian/diff
    - sebastian/comparator
    - symfony/yaml
    - doctrine/instantiator
    - phpunit/php-text-template
    - phpunit/phpunit-mock-objects
    - phpunit/php-timer
    - phpunit/php-file-iterator
    - phpunit/php-token-stream
    - phpunit/php-code-coverage
    - phpunit/phpunit
    - phpspec/php-diff
    - phpdocumentor/reflection-docblock
    - phpspec/prophecy
    - dflydev/markdown
    - phpspec/phpspec
    - laravel/laravel
    - phpunit/dbunit
    - ocramius/instantiator
    - ocramius/lazy-map
    - illuminate/auth
    - illuminate/bus
    - illuminate/cache
    - illuminate/config
    - illuminate/console
    - illuminate/container
    - illuminate/contracts
    - illuminate/cookie
    - illuminate/database
    - illuminate/encryption
    - illuminate/events
    - illuminate/exception
    - illuminate/filesystem
    - illuminate/foundation
    - illuminate/hashing
    - illuminate/http
    - illuminate/log
    - illuminate/mail
    - illuminate/pagination
    - illuminate/pipeline
    - illuminate/queue
    - illuminate/redis
    - illuminate/routing
    - illuminate/session
    - illuminate/support
    - illuminate/translation
    - illuminate/validation
    - illuminate/view
    - barryvdh/laravel-ide-helper
    - symfony/class-loader
    - jenssegers/agent
    - mobiledetect/mobiledetectlib
    - james-heinrich/getid3
    - symfony/dom-crawler
    - symfony/css-selector
    - symfony/browser-kit
    - stack/builder
    - predis/predis
    - phpseclib/phpseclib
    - patchwork/utf8
    - filp/whoops
    - d11wtq/boris
    - doctrine/lexer
    - doctrine/annotations
    - doctrine/collections
    - doctrine/cache
    - doctrine/common
    - doctrine/dbal
    - intervention/image
    - tijsverkoyen/css-to-inline-styles
    - phpoffice/phpexcel
    - maatwebsite/excel
    - symfony/security
    - illuminate/html
    - illuminate/remote
    - illuminate/workbench
    - symfony/security-acl
    - symfony/security-csrf
    - symfony/security-http
    - october/october
    - october/system
    - october/backend
    - october/cms
    - october/rain
    - composer/installers
    - erusev/parsedown-extra
    - kriswallsmith/assetic
    - linkorb/jsmin-php
    - oyejorge/less.php
    - twig/twig
    - guzzlehttp/guzzle
    - league/csv
    - erusev/parsedown
    - guzzlehttp/streams
    - october/auth
    - october/config
    - october/cron
    - october/database
    - october/extension
    - october/filesystem
    - october/html
    - october/mail
    - october/network
    - october/router
    - october/support
    - october/syntax
    - october/translation
    - laravel/installer
    - cartalyst/sentry
    - fzaninotto/faker
    - lucadegasperi/oauth2-server-laravel
    - league/oauth2-server
    - league/event
    - barryvdh/laravel-cors
    - asm89/stack-cors
    - barryvdh/laravel-debugbar
    - maximebf/debugbar
    - zizaco/confide
    - zizaco/entrust
    - laravelbook/ardent
    - frozennode/administrator
    - ckeditor/ckeditor
    - way/generators
    - yiisoft/yii2-app-basic
    - yiisoft/yii2
    - yiisoft/yii2-bootstrap
    - yiisoft/yii2-swiftmailer
    - yiisoft/yii2-composer
    - ezyang/htmlpurifier
    - cebe/markdown
    - yiisoft/yii2-codeception
    - yiisoft/yii2-debug
    - yiisoft/yii2-gii
    - yiisoft/yii2-faker
    - fxp/composer-asset-plugin
    - phalcon/devtools
    - sonata-project/core-bundle
    - raulfraile/ladybug-bundle
    - jms/security-extra-bundle
    - jms/translation-bundle
    - nelmio/cors-bundle
    - dwd/qiniu-sdk-bundle
    - sonata-project/doctrine-orm-admin-bundle
    - jms/serializer-bundle
    - sonata-project/admin-bundle
    - zhuzhichao/ip-location-zh
    - raulfraile/ladybug-installer
    - jdorn/sql-formatter
    - symfony/doctrine-bridge
    - symfony/framework-bundle
    - doctrine/doctrine-bundle
    - symfony/config
    - symfony/stopwatch
    - symfony/dependency-injection
    - symfony/templating
    - doctrine/data-fixtures
    - doctrine/doctrine-fixtures-bundle
    - cocur/slugify
    - symfony/form
    - symfony/intl
    - symfony/options-resolver
    - celc/ciunit
    - mustangostang/spyc
    - yiisoft/yii2-app-advanced
    - kartik-v/yii2-grid
    - kartik-v/yii2-krajee-base
    - kartik-v/yii2-widgets
    - kartik-v/bootstrap-star-rating
    - kartik-v/bootstrap-fileinput
    - kartik-v/dependent-dropdown
    - kartik-v/yii2-field-range
    - kartik-v/yii2-widget-activeform
    - kartik-v/yii2-widget-affix
    - kartik-v/yii2-widget-alert
    - kartik-v/yii2-widget-colorinput
    - kartik-v/yii2-widget-datepicker
    - kartik-v/yii2-widget-datetimepicker
    - kartik-v/yii2-widget-depdrop
    - kartik-v/yii2-widget-fileinput
    - kartik-v/yii2-widget-growl
    - kartik-v/yii2-widget-rangeinput
    - kartik-v/yii2-widget-rating
    - kartik-v/yii2-widget-select2
    - kartik-v/yii2-widget-sidenav
    - kartik-v/yii2-widget-spinner
    - kartik-v/yii2-widget-switchinput
    - kartik-v/yii2-widget-timepicker
    - kartik-v/yii2-widget-touchspin
    - kartik-v/yii2-widget-typeahead
    - mikecao/flight
    - phpoption/phpoption
    - jms/parser-lib
    - leaps/httpclient
    - leaps/events
    - leaps/filesystem
    - leaps/framework
    - vlucas/valitron
    - yiisoft/jquery
    - michelf/php-markdown
    - yiisoft/jquery-pjax
    - twbs/bootstrap
    - symfony/symfony
    - doctrine/orm
    - twig/extensions
    - symfony/assetic-bundle
    - symfony/swiftmailer-bundle
    - symfony/monolog-bundle
    - sensio/distribution-bundle
    - sensio/framework-extra-bundle
    - sensio/generator-bundle
    - incenteev/composer-parameter-handler
    - nelmio/api-doc-bundle
    - misd/guzzle-bundle
    - iknowapp/baidu-push-sdk
    - symfony/framework-standard-edition
    - symfony/icu
    - symfony/swiftmailer-bridge
    - symfony/monolog-bridge
    - symfony/twig-bundle
    - jms/serializer
    - symfony/security-bundle
    - jms/metadata
    - jms/aop-bundle
    - jms/di-extra-bundle
    - guzzle/guzzle
    - symfony/twig-bridge
    - phpcollection/phpcollection
    - jms/cg
    - symfony/locale
    - symfony/propel1-bridge
    - symfony/property-access
    - symfony/proxy-manager-bridge
    - symfony/serializer
    - symfony/validator
    - symfony/web-profiler-bundle
    - symfony/expression-language
    - guzzle/batch
    - guzzle/cache
    - guzzle/common
    - guzzle/http
    - guzzle/inflection
    - guzzle/iterator
    - guzzle/log
    - guzzle/parser
    - guzzle/plugin
    - guzzle/plugin-async
    - guzzle/plugin-backoff
    - guzzle/plugin-cache
    - guzzle/plugin-cookie
    - guzzle/plugin-curlauth
    - guzzle/plugin-history
    - guzzle/plugin-log
    - guzzle/plugin-mock
    - guzzle/plugin-oauth
    - guzzle/service
    - guzzle/stream
    - guzzle/plugin-md5
    - guzzle/plugin-error-response
    - pimple/pimple
    - saxulum/saxulum-assetic-twig-provider
    - silex/silex
    - kilte/silex-captcha
    - silex/web-profiler
    - mrclay/minify
    - gregwar/captcha
    - silex/api
    - silex/providers
    - composer/satis
    - composer/composer
    - justinrainbow/json-schema
    - seld/jsonlint
    - saxulum/saxulum-console
    - firephp/firephp-core
    - tubalmartin/cssmin
    - doctrine/doctrine-cache-bundle
    - sorien/silex-dbal-profiler
    - tymon/jwt-auth
    - namshi/jose
    - dflydev/doctrine-orm-service-provider
    - affinitidev/silex-config
    - sami/sami
packagist_sync: proxy
dist_sync_mode: lazy
git_prefix: false
git_path: false
license: null
license_personal: true
