repositories: {  }
packagist_packages:
    - vlucas/phpdotenv
    - symfony/var-dumper
    - symfony/translation
    - symfony/security-core
    - symfony/routing
    - symfony/process
    - psr/log
    - symfony/debug
    - symfony/http-foundation
    - symfony/event-dispatcher
    - symfony/http-kernel
    - symfony/finder
    - symfony/console
    - swiftmailer/swiftmailer
    - jakub-onderka/php-console-color
    - jakub-onderka/php-console-highlighter
    - dnoegel/php-xdg-base-dir
    - nikic/php-parser
    - psy/psysh
packagist_sync: proxy
dist_sync_mode: lazy
git_prefix: false
git_path: false
license: null
license_personal: true
