repositories: {  }
packagist_packages:
    - vlucas/phpdotenv
    - symfony/var-dumper
    - symfony/translation
    - symfony/security-core
    - symfony/routing
    - symfony/process
    - psr/log
    - symfony/debug
    - symfony/http-foundation
    - symfony/event-dispatcher
    - symfony/http-kernel
    - symfony/finder
    - symfony/console
    - swiftmailer/swiftmailer
    - jakub-onderka/php-console-color
    - jakub-onderka/php-console-highlighter
    - dnoegel/php-xdg-base-dir
    - nikic/php-parser
    - psy/psysh
    - nesbot/carbon
    - mtdowling/cron-expression
    - monolog/monolog
    - league/flysystem
    - jeremeamia/superclosure
    - ircmaxell/password-compat
    - doctrine/inflector
    - danielstjules/stringy
    - symfony/filesystem
    - classpreloader/classpreloader
    - laravel/framework
    - sebastian/version
    - sebastian/global-state
    - sebastian/recursion-context
    - sebastian/exporter
    - sebastian/environment
    - sebastian/diff
    - sebastian/comparator
    - symfony/yaml
    - doctrine/instantiator
    - phpunit/php-text-template
    - phpunit/phpunit-mock-objects
    - phpunit/php-timer
    - phpunit/php-file-iterator
    - phpunit/php-token-stream
    - phpunit/php-code-coverage
    - phpunit/phpunit
    - phpspec/php-diff
    - phpdocumentor/reflection-docblock
    - phpspec/prophecy
    - dflydev/markdown
    - phpspec/phpspec
    - laravel/laravel
    - phpunit/dbunit
    - ocramius/instantiator
    - ocramius/lazy-map
    - illuminate/auth
    - illuminate/bus
    - illuminate/cache
    - illuminate/config
    - illuminate/console
    - illuminate/container
    - illuminate/contracts
    - illuminate/cookie
    - illuminate/database
    - illuminate/encryption
    - illuminate/events
    - illuminate/exception
    - illuminate/filesystem
    - illuminate/foundation
    - illuminate/hashing
    - illuminate/http
    - illuminate/log
    - illuminate/mail
    - illuminate/pagination
    - illuminate/pipeline
    - illuminate/queue
    - illuminate/redis
    - illuminate/routing
    - illuminate/session
    - illuminate/support
    - illuminate/translation
    - illuminate/validation
    - illuminate/view
    - barryvdh/laravel-ide-helper
    - symfony/class-loader
    - jenssegers/agent
    - mobiledetect/mobiledetectlib
    - james-heinrich/getid3
    - symfony/dom-crawler
    - symfony/css-selector
    - symfony/browser-kit
    - stack/builder
    - predis/predis
    - phpseclib/phpseclib
    - patchwork/utf8
    - filp/whoops
    - d11wtq/boris
    - doctrine/lexer
    - doctrine/annotations
    - doctrine/collections
    - doctrine/cache
    - doctrine/common
    - doctrine/dbal
    - intervention/image
    - tijsverkoyen/css-to-inline-styles
    - phpoffice/phpexcel
    - maatwebsite/excel
    - symfony/security
    - illuminate/html
    - illuminate/remote
    - illuminate/workbench
    - symfony/security-acl
    - symfony/security-csrf
    - symfony/security-http
packagist_sync: proxy
dist_sync_mode: lazy
git_prefix: false
git_path: false
license: null
license_personal: true
