repositories: {  }
packagist_packages:
    - barryvdh/laravel-ide-helper
    - james-heinrich/getid3
    - symfony/translation
    - symfony/security-core
    - symfony/routing
    - symfony/process
    - psr/log
    - symfony/debug
    - symfony/http-foundation
    - symfony/event-dispatcher
    - symfony/http-kernel
    - symfony/finder
    - symfony/dom-crawler
    - symfony/css-selector
    - symfony/console
    - symfony/browser-kit
    - swiftmailer/swiftmailer
    - stack/builder
    - predis/predis
    - phpseclib/phpseclib
    - patchwork/utf8
    - nesbot/carbon
    - monolog/monolog
    - nikic/php-parser
    - jeremeamia/superclosure
    - filp/whoops
    - ircmaxell/password-compat
    - d11wtq/boris
    - symfony/filesystem
    - classpreloader/classpreloader
    - laravel/framework
    - phpdocumentor/reflection-docblock
    - symfony/class-loader
    - illuminate/console
    - illuminate/filesystem
    - illuminate/support
    - dflydev/markdown
    - doctrine/lexer
    - doctrine/annotations
    - doctrine/collections
    - doctrine/cache
    - doctrine/inflector
    - doctrine/common
    - doctrine/dbal
    - intervention/image
    - mobiledetect/mobiledetectlib
    - jenssegers/agent
    - tijsverkoyen/css-to-inline-styles
    - phpoffice/phpexcel
    - illuminate/cache
    - illuminate/config
    - illuminate/http
    - illuminate/routing
    - illuminate/view
    - maatwebsite/excel
    - illuminate/database
    - illuminate/encryption
    - illuminate/redis
    - illuminate/session
    - illuminate/container
    - illuminate/events
    - illuminate/cookie
    - symfony/security
    - laravel/laravel
    - illuminate/auth
    - illuminate/exception
    - illuminate/foundation
    - illuminate/hashing
    - illuminate/html
    - illuminate/log
    - illuminate/mail
    - illuminate/pagination
    - illuminate/queue
    - illuminate/remote
    - illuminate/translation
    - illuminate/validation
    - illuminate/workbench
    - symfony/security-acl
    - symfony/security-csrf
    - symfony/security-http
packagist_sync: proxy
dist_sync_mode: lazy
git_prefix: false
git_path: false
license: null
license_personal: true
